spring.application.name=teachify

spring.datasource.url=jdbc:mysql://localhost:3306/teachify-app
spring.datasource.username=root
spring.datasource.password=ayush

security.jwt.secret-key=e50a94505dd4543ad7a06ab98c4e0821233eaca26f5bda764eb69656a195c779
#1h in milisecond
security.jwt.expiration-time=3600000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect